# Generated by Django 4.2.6 on 2023-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_stories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_title', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Первый блог',
                'verbose_name_plural': 'Первые блоги',
            },
        ),
    ]
