# Generated by Django 4.2.6 on 2023-10-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_stories_image'),
        ('category', '0002_rename_category_title_firstblog_category_titlee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Второй блог',
                'verbose_name_plural': 'Вторые блоги',
            },
        ),
    ]
