# Generated by Django 4.2.6 on 2023-10-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_stories_image'),
        ('category', '0004_remove_firstblog_category_titlee_firstblog_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstblog',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_title', to='blog.category', verbose_name='Категория которую будете отображать'),
        ),
    ]
