# Generated by Django 4.2.6 on 2023-10-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_firstblog_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstblog',
            old_name='first',
            new_name='category_titlee',
        ),
    ]
