# Generated by Django 4.2.6 on 2023-10-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_stories_image'),
        ('category', '0007_remove_firstblog_category_titlee_firstblog_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Третий блог',
                'verbose_name_plural': 'Третий блог',
            },
        ),
    ]
