# Generated by Django 4.2.6 on 2023-10-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('url_booking', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Большая реклама',
                'verbose_name_plural': 'Большие рекламы',
            },
        ),
    ]
