# Generated by Django 4.2.6 on 2023-10-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_bigadvert_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Баннер в размере 970х90 - 1200х120')),
                ('url_booking', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Cредняя реклама',
                'verbose_name_plural': 'Средние рекламы',
            },
        ),
        migrations.CreateModel(
            name='SmallAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Баннер в размере 250x250')),
                ('url_booking', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Cредняя реклама',
                'verbose_name_plural': 'Средние рекламы',
            },
        ),
    ]
