# Generated by Django 4.2.6 on 2023-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_normaladvert_smalladvert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smalladvert',
            options={'verbose_name': 'Маленькая реклама', 'verbose_name_plural': 'Маленькие рекламы'},
        ),
        migrations.AlterField(
            model_name='normaladvert',
            name='image',
            field=models.ImageField(upload_to='normaladvert_image', verbose_name='Баннер в размере 970х90 - 1200х120'),
        ),
        migrations.AlterField(
            model_name='smalladvert',
            name='image',
            field=models.ImageField(upload_to='smalladvert_image', verbose_name='Баннер в размере 250x250'),
        ),
    ]
