# Generated by Django 4.2.6 on 2023-10-18 17:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_alter_smalladvert_options_alter_normaladvert_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigadvert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='bigadvert_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='normaladvert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='normadvert_image/', verbose_name='Баннер в размере 970х90 - 1200х120'),
        ),
        migrations.AlterField(
            model_name='smalladvert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='smalladvert_image/', verbose_name='Баннер в размере 250x250'),
        ),
    ]
