# Generated by Django 4.2.7 on 2023-11-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('all_categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstBlogDetail',
            new_name='D1Blog',
        ),
    ]
