# Generated by Django 4.2.7 on 2023-11-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
        ('all_categories', '0004_alter_firstblog_options_alter_fiveoneblog_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstBlog',
            new_name='B1Blog',
        ),
    ]
