# Generated by Django 4.2.7 on 2023-11-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
        ('all_categories', '0005_rename_firstblog_b1blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondBlog',
            new_name='B2Blog',
        ),
    ]
