# Generated by Django 4.2.7 on 2023-11-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
        ('all_categories', '0007_rename_thirdblog_b3blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FourBlog',
            new_name='B4Blog',
        ),
    ]
