# Generated by Django 4.2.7 on 2023-11-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
        ('all_categories', '0008_rename_fourblog_b4blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiveOneBlog',
            new_name='B5Blog',
        ),
    ]
