# Generated by Django 4.2.7 on 2023-11-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
        ('all_categories', '0009_rename_fiveoneblog_b5blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiveTwoBlog',
            new_name='B6Blog',
        ),
    ]
