# Generated by Django 4.2.7 on 2024-01-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_banner_image_alter_magazine_image_and_more'),
        ('all_categories', '0011_rename_fivethreeblog_b7blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B7Blog',
            new_name='B8Blog',
        ),
        migrations.AlterModelOptions(
            name='b8blog',
            options={'verbose_name': 'Изменить категорию для B8', 'verbose_name_plural': 'Изменить категорию для B8'},
        ),
    ]
