# Generated by Django 4.2.7 on 2024-01-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_banner_image_alter_magazine_image_and_more'),
        ('all_categories', '0012_rename_b7blog_b8blog_alter_b8blog_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B8Blog',
            new_name='B11Blog',
        ),
        migrations.AlterModelOptions(
            name='b11blog',
            options={'verbose_name': 'Изменить категорию для B11', 'verbose_name_plural': 'Изменить категорию для B11'},
        ),
    ]
