# Generated by Django 4.2.7 on 2024-01-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_banner_image_alter_magazine_image_and_more'),
        ('all_categories', '0013_rename_b8blog_b11blog_alter_b11blog_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B6Blog',
            new_name='B10Blog',
        ),
        migrations.RenameModel(
            old_name='B5Blog',
            new_name='B9Blog',
        ),
        migrations.AlterModelOptions(
            name='b10blog',
            options={'verbose_name': 'Изменить категорию для B10', 'verbose_name_plural': 'Изменить категорию для B10'},
        ),
        migrations.AlterModelOptions(
            name='b9blog',
            options={'verbose_name': 'Изменить категорию для B9', 'verbose_name_plural': 'Изменить категорию для B9'},
        ),
    ]
