# Generated by Django 4.2.7 on 2024-01-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_banner_image_alter_magazine_image_and_more'),
        ('all_categories', '0014_rename_b6blog_b10blog_rename_b5blog_b9blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B8Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Изменить категорию для B4',
                'verbose_name_plural': 'Изменить категорию для B4',
            },
        ),
        migrations.CreateModel(
            name='B7Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Изменить категорию для B4',
                'verbose_name_plural': 'Изменить категорию для B4',
            },
        ),
        migrations.CreateModel(
            name='B6Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Изменить категорию для B4',
                'verbose_name_plural': 'Изменить категорию для B4',
            },
        ),
        migrations.CreateModel(
            name='B5Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five_category', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Изменить категорию для B4',
                'verbose_name_plural': 'Изменить категорию для B4',
            },
        ),
    ]
