# Generated by Django 4.2.7 on 2024-01-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_categories', '0015_b8blog_b7blog_b6blog_b5blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b10blog',
            options={'verbose_name': '10) Изменить категорию для B 10', 'verbose_name_plural': '10) Изменить категорию для B 10'},
        ),
        migrations.AlterModelOptions(
            name='b11blog',
            options={'verbose_name': '11) Изменить категорию для B11', 'verbose_name_plural': '11)  Изменить категорию для B11'},
        ),
        migrations.AlterModelOptions(
            name='b1blog',
            options={'verbose_name': '1) Изменить категорию для B1', 'verbose_name_plural': '1) Изменить категорию для B1'},
        ),
        migrations.AlterModelOptions(
            name='b2blog',
            options={'verbose_name': '2) Изменить категорию для B2', 'verbose_name_plural': '2) Изменить категорию для B2'},
        ),
        migrations.AlterModelOptions(
            name='b3blog',
            options={'verbose_name': '3) Изменить категорию для B3', 'verbose_name_plural': '3)  Изменить категорию для B3'},
        ),
        migrations.AlterModelOptions(
            name='b4blog',
            options={'verbose_name': '4)  Изменить категорию для B4', 'verbose_name_plural': ' 4) Изменить категорию для B4'},
        ),
        migrations.AlterModelOptions(
            name='b5blog',
            options={'verbose_name': '5) Изменить категорию для B5', 'verbose_name_plural': '5) Изменить категорию для B5'},
        ),
        migrations.AlterModelOptions(
            name='b6blog',
            options={'verbose_name': '6) Изменить категорию для B6', 'verbose_name_plural': '6) Изменить категорию для B6'},
        ),
        migrations.AlterModelOptions(
            name='b7blog',
            options={'verbose_name': '7) Изменить категорию для B7', 'verbose_name_plural': '7) Изменить категорию для B7'},
        ),
        migrations.AlterModelOptions(
            name='b8blog',
            options={'verbose_name': '8) Изменить категорию для B8', 'verbose_name_plural': '8) Изменить категорию для B8'},
        ),
        migrations.AlterModelOptions(
            name='b9blog',
            options={'verbose_name': '9) Изменить категорию для B9', 'verbose_name_plural': '9) Изменить категорию для B9'},
        ),
    ]
