# Generated by Django 4.2.7 on 2024-01-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_categories', '0016_alter_b10blog_options_alter_b11blog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b10blog',
            options={'verbose_name': 'Изменить категорию для B10', 'verbose_name_plural': 'Изменить категорию для B10'},
        ),
        migrations.AlterModelOptions(
            name='b11blog',
            options={'verbose_name': 'Изменить категорию для B11', 'verbose_name_plural': 'Изменить категорию для B11'},
        ),
        migrations.AlterModelOptions(
            name='b1blog',
            options={'verbose_name': 'Изменить категорию для B1', 'verbose_name_plural': 'Изменить категорию для B1'},
        ),
        migrations.AlterModelOptions(
            name='b2blog',
            options={'verbose_name': 'Изменить категорию для B2', 'verbose_name_plural': 'Изменить категорию для B2'},
        ),
        migrations.AlterModelOptions(
            name='b3blog',
            options={'verbose_name': 'Изменить категорию для B3', 'verbose_name_plural': ' Изменить категорию для B3'},
        ),
        migrations.AlterModelOptions(
            name='b4blog',
            options={'verbose_name': 'Изменить категорию для B4', 'verbose_name_plural': ' Изменить категорию для B4'},
        ),
        migrations.AlterModelOptions(
            name='b5blog',
            options={'verbose_name': 'Изменить категорию для B5', 'verbose_name_plural': 'Изменить категорию для B5'},
        ),
        migrations.AlterModelOptions(
            name='b6blog',
            options={'verbose_name': 'Изменить категорию для B6', 'verbose_name_plural': 'Изменить категорию для B6'},
        ),
        migrations.AlterModelOptions(
            name='b7blog',
            options={'verbose_name': 'Изменить категорию для B7', 'verbose_name_plural': 'Изменить категорию для B7'},
        ),
        migrations.AlterModelOptions(
            name='b8blog',
            options={'verbose_name': 'Изменить категорию для B8', 'verbose_name_plural': 'Изменить категорию для B8'},
        ),
        migrations.AlterModelOptions(
            name='b9blog',
            options={'verbose_name': 'Изменить категорию для B9', 'verbose_name_plural': 'Изменить категорию для B9'},
        ),
    ]
