# Generated by Django 4.2.7 on 2023-11-08 04:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='team_image/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('work', models.CharField(max_length=255, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Наша комманда',
                'verbose_name_plural': 'Наша комманда',
            },
        ),
    ]
