# Generated by Django 4.2.7 on 2023-11-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наша история',
                'verbose_name_plural': 'Наша истории',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Наша комманда', 'verbose_name_plural': 'Наша комманды'},
        ),
    ]
