# Generated by Django 4.2.7 on 2024-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_partners_descriptions_partners_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.CharField(max_length=255, verbose_name='Доллар')),
                ('euro', models.CharField(max_length=255, verbose_name='Евро')),
                ('rub', models.CharField(max_length=255, verbose_name='Рубль')),
                ('tenge', models.CharField(max_length=255, verbose_name='Тенге')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курс валют',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Погода')),
            ],
        ),
    ]
