# Generated by Django 4.2.7 on 2024-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_currency_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='title',
            new_name='weather_condition',
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.CharField(default=1, max_length=255, verbose_name='Температура'),
            preserve_default=False,
        ),
    ]
