# Generated by Django 4.2.7 on 2024-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_rename_title_weather_weather_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_condition',
            field=models.CharField(max_length=255, null=True, verbose_name='Погода'),
        ),
    ]
