# Generated by Django 4.2.7 on 2024-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_weather_weather_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.CharField(max_length=255, null=True, verbose_name='Температура'),
        ),
    ]
