# Generated by Django 4.2.7 on 2024-02-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_alter_weather_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
    ]
