# Generated by Django 4.2.6 on 2023-10-14 04:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('info_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_blog/', verbose_name='Видео материал')),
                ('image', models.ImageField(upload_to='Image_blog/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BlogSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('blog_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_subtitle', to='blog.blog', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Дополнительный подзаголовок',
                'verbose_name_plural': 'Дополнительные подзаголовоки',
            },
        ),
        migrations.CreateModel(
            name='BlogInfoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
                ('blog_infotext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_infotext', to='blog.blog', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Дополнительный информационный текст',
                'verbose_name_plural': 'Дополнительные информационные тексты',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='blog_images/', verbose_name='Основная фотография')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='blog.blog', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Картинка новстей',
                'verbose_name_plural': 'Картинки новстей',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='blog.category', verbose_name='Категории'),
        ),
    ]
