# Generated by Django 4.2.7 on 2023-11-08 05:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='bigadvert_image/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('url_booking', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Большая реклама',
                'verbose_name_plural': 'Большие рекламы',
            },
        ),
        migrations.CreateModel(
            name='NormalAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='normadvert_image/', verbose_name='Баннер в размере 970х90 - 1200х120')),
                ('url_booking', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Cредняя реклама',
                'verbose_name_plural': 'Средние рекламы',
            },
        ),
        migrations.CreateModel(
            name='SmallAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='smalladvert_image/', verbose_name='Баннер в размере 250x250')),
                ('url_booking', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Маленькая реклама',
                'verbose_name_plural': 'Маленькие рекламы',
            },
        ),
    ]
