# Generated by Django 4.2.6 on 2023-10-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfotext',
            name='blog_infotext',
        ),
        migrations.RemoveField(
            model_name='blogsubtitle',
            name='blog_subtitle',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogInfoText',
        ),
        migrations.DeleteModel(
            name='BlogSubTitle',
        ),
    ]
