# Generated by Django 4.2.6 on 2023-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='info_text',
            field=models.TextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
