# Generated by Django 4.2.6 on 2023-10-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_info_text_blog_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_blog/', verbose_name='Видео материал'),
        ),
    ]
