# Generated by Django 4.2.7 on 2023-11-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_normaladvert_options_alter_smalladvert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigadvert',
            options={'verbose_name': 'Добавить рекламу большого масштаба', 'verbose_name_plural': 'Добавить рекламу большого масштаба'},
        ),
        migrations.AlterModelOptions(
            name='smalladvert',
            options={'verbose_name': 'Добавить рекламу маленького масштаба', 'verbose_name_plural': 'Добавить рекламу маленького масштаба'},
        ),
    ]
