# Generated by Django 4.2.7 on 2023-11-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_bigadvert_options_alter_smalladvert_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
