# Generated by Django 4.2.6 on 2023-10-14 04:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='descriptions',
        ),
        migrations.AlterField(
            model_name='blog',
            name='info_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок '),
        ),
    ]
