# Generated by Django 4.2.6 on 2023-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_stories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdBlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_title_detail', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Третий блог в детальном просмотере',
                'verbose_name_plural': 'Третие блоги в детальном просмотере',
            },
        ),
        migrations.CreateModel(
            name='SecondBlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_title_detail', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Второй блог в детальном просмотере',
                'verbose_name_plural': 'Вторые блоги в детальном просмотере',
            },
        ),
        migrations.CreateModel(
            name='FirstBlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_title_detail', to='blog.category', verbose_name='Категория которую будете отображать')),
            ],
            options={
                'verbose_name': 'Первый блог в детальном просмотере',
                'verbose_name_plural': 'Первые блоги в детальном просмотере',
            },
        ),
    ]
