# Generated by Django 4.2.6 on 2023-10-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_descriptions_alter_blog_info_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('blog_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_subtitle', to='blog.blog', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Дополнительный подзаголовок',
                'verbose_name_plural': 'Дополнительные подзаголовоки',
            },
        ),
        migrations.CreateModel(
            name='BlogInfoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('blog_infotext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_infotext', to='blog.blog', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Дополнительный информационный текст',
                'verbose_name_plural': 'Дополнительные информационные тексты',
            },
        ),
    ]
