# Generated by Django 4.2.6 on 2023-10-14 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogsubtitle_bloginfotext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfotext',
            name='info_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
