# Generated by Django 4.2.7 on 2023-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_magazine_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(max_length=255, upload_to='', verbose_name='Фотография')),
                ('url', models.URLField(verbose_name='Ccылка')),
            ],
            options={
                'verbose_name': 'Баннер на главной странице',
                'verbose_name_plural': 'Баннеры на главной странице',
            },
        ),
    ]
