# Generated by Django 4.2.7 on 2023-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(default=1, upload_to='service_magazine', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
