# Generated by Django 4.2.7 on 2024-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_magazine_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Услуга Журнала', 'verbose_name_plural': 'Услуги Журнала'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Услуга Сайта', 'verbose_name_plural': 'Услуги Сайта'},
        ),
        migrations.AddField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
