# Generated by Django 4.2.7 on 2024-01-05 14:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_magazine_options_alter_site_options_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='banner/', verbose_name='Баннер в размере '),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Баннер в размере '),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Баннер в размере '),
        ),
    ]
