# Generated by Django 4.2.7 on 2024-01-16 00:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_banner_image_alter_magazine_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Баннер в размере 267х189'),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Баннер в размере 267х189'),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография ')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_image', to='blog.site')),
            ],
            options={
                'verbose_name': 'Дополнительная фотограя сайта',
                'verbose_name_plural': 'Дополнительная фотограя баннера',
                'unique_together': {('settings', 'image')},
            },
        ),
        migrations.CreateModel(
            name='MagazineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_image', to='blog.magazine')),
            ],
            options={
                'verbose_name': 'Дополнительная фотограя баннера в размере 267х189',
                'verbose_name_plural': 'Дополнительная фотограя баннера в размере 267х189',
                'unique_together': {('settings', 'image')},
            },
        ),
    ]
