# Generated by Django 4.2.6 on 2023-10-28 12:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='profile_image/', verbose_name='Фотография'),
        ),
    ]
