# Generated by Django 4.2.7 on 2023-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Отправить рассылку', 'verbose_name_plural': 'Отправить рассылку'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Заговолок'),
        ),
    ]
