# Generated by Django 4.2.7 on 2023-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newsletter_options_alter_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='newsletter_attachments/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
