# Generated by Django 4.2.7 on 2023-12-01 00:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newsletter_attachment_newsletter_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Сообщение'),
        ),
    ]
