# Generated by Django 4.2.7 on 2024-01-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_magazine_descriptions'),
        ('users', '0012_serviceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMagazineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_magazine_form', to='blog.magazine')),
            ],
            options={
                'verbose_name': 'Заявки на услуги магазина',
                'verbose_name_plural': 'Заявка на услугу магазина',
            },
        ),
        migrations.CreateModel(
            name='ServiceSiteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_site_form', to='blog.site')),
            ],
            options={
                'verbose_name': 'Заявки на услуги cайта',
                'verbose_name_plural': 'Заявка на услугу cайта',
            },
        ),
        migrations.DeleteModel(
            name='ServiceForm',
        ),
    ]
