# Generated by Django 4.2.7 on 2024-01-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_servicemagazineform_servicesiteform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemagazineform',
            name='service',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='servicesiteform',
            name='service',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
