# Generated by Django 4.2.7 on 2024-01-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_servicemagazineform_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lohi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Жалобы пользователей',
                'verbose_name_plural': 'Жалобы пользователей',
            },
        ),
    ]
