# Generated by Django 4.2.7 on 2024-02-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_lohi_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявки на партнерства',
                'verbose_name_plural': 'Заявка на партнерства',
            },
        ),
    ]
