# Generated by Django 4.2.7 on 2023-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
    ]
