# Generated by Django 4.2.7 on 2023-12-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_option_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vote.nomination'),
        ),
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
