# Generated by Django 4.2.7 on 2023-12-17 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0004_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='nomination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.nomination', verbose_name='Номинация'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'nomination')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
    ]
