# Generated by Django 4.2.7 on 2023-12-18 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_voting_descriptions_voting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
