# Generated by Django 4.2.7 on 2023-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_alter_voting_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания голосования')),
            ],
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
