# Generated by Django 4.2.7 on 2023-12-20 02:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_votinginfo_delete_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinginfo',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
