# Generated by Django 4.2.6 on 2023-10-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='descriptions_contacts',
        ),
    ]
