# Generated by Django 4.2.7 on 2023-11-08 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
