# Generated by Django 4.2.6 on 2023-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_settings_descriptions_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
    ]
