# Generated by Django 4.2.6 on 2023-10-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_settings_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
