# Generated by Django 4.2.7 on 2023-11-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_stories_alter_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
