# Generated by Django 4.2.6 on 2023-10-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Наша комманда', 'verbose_name_plural': 'Наша комманда'},
        ),
    ]
