# Generated by Django 4.2.7 on 2023-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_settings_logo_white_alter_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Информационный текст'),
        ),
    ]
