# Generated by Django 4.2.7 on 2023-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('document', models.FileField(upload_to='', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Журналы',
                'verbose_name_plural': 'Журнал',
            },
        ),
    ]
