# Generated by Django 4.2.7 on 2023-11-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='magazine_images/')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='magazine.magazine')),
            ],
        ),
    ]
