# Generated by Django 4.2.7 on 2023-11-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazineimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagazineImage',
        ),
    ]
