# Generated by Django 4.2.7 on 2023-11-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_rename_document_magazine_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='magazines')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.magazine')),
            ],
        ),
    ]
