# Generated by Django 4.2.7 on 2023-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_magazineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='magazines'),
        ),
        migrations.DeleteModel(
            name='MagazineImage',
        ),
    ]
