# Generated by Django 4.2.7 on 2023-11-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_magazine_image_delete_magazineimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='image',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf',
            field=models.FileField(upload_to='pdfs', verbose_name='Журнал'),
        ),
    ]
