# Generated by Django 4.2.7 on 2023-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_alter_magazine_options_remove_magazine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='pdf',
            field=models.FileField(upload_to='pdfs', verbose_name='PDF файл'),
        ),
    ]
